### ISSUE TITLE
Regression test "integration.strlen (strlen.thumb.gcc.O0.g.elf)" fails on macOS

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec#264]
The `integration.strlen.Test_2017 (strlen.thumb.gcc.O0.g.elf)` regression test fails on macOS but succeeds on Linux and Windows.

## Input

Run the following regression test via [our testing framework](https://github.com/avast-tl/retdec-regression-tests-framework):
```
$ runner.py integration.strlen -r 'Test_2017.*strlen.thumb.gcc.O0.g.elf'
```

## Output

The test fails:
```
integration.strlen.Test_2017 (strlen.thumb.gcc.O0.g.elf)        [ FAIL ]  (5.85s)
F
======================================================================
FAIL: test_produce_expected_output (integration.strlen.Test_2017)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "retdec-regression-tests/integration/strlen/test.py", line 12, in test_produce_expected_output
   expected_return_code=52
 File "retdec-regression-tests-framework/regression_tests/tools/decompiler_test.py", line 86, in assert_c_produces_output_when_run
   self.assertEqual(actual_return_code, expected_return_code, msg)
AssertionError: -6 != 52 : where the input was: aaaaaaaaaabbbbbbbbbbbbbbbbccccccccccccccdddddddddddd

----------------------------------------------------------------------
Ran 1 test in 0.214s

FAILED (failures=1)
```

## Expected output

The test should pass:
```
integration.strlen.Test_2017 (strlen.thumb.gcc.O0.g.elf)        [  OK  ]  (5.72s)
```

## Configuration

* Commit: ae9a6d412caf73f1c93c7012a6f799de0cc95cdb (current `master`)
* 64b Arch Linux, GCC 7.3.1, Release build of RetDec
* mac OS 10.13, Apple LLVM version 9.0.0, Release build of RetDec

**Comment by s3rvac** [comment]
Here is an analysis of the issue. On both Linux and macOS, the input binary file is decompiled into the same C code (showing just `main()` as the other parts are irrelevant):
```c
int main(int argc, char ** argv) {
    char text[256]; // bp-268
    int32_t v1 = (int32_t)&argv; // 0x85aa
    scanf("%s", &text);
    *(int32_t *)(v1 + 268) = my_strlen(text);
    printf("%d\n", *(int32_t *)(v1 + 268));
    return *(int32_t *)(v1 + 268);
}
```
In the test, we expect the compiled decompiled code to print `52\n` and exit with return code `52` when run with the following input:
```python
    def test_produce_expected_output(self):
        self.assert_c_produces_output_when_run(
            input='aaaaaaaaaabbbbbbbbbbbbbbbbccccccccccccccdddddddddddd',
            expected_output='52\n',
            expected_return_code=52
          )
```
On Linux, it prints `52\n` and exits with `52`, so the test succeeds. On macOS, it prints `52\n`, but then it prints `Abort trap: 6` exits with return code `134` (`SIGABRT`). The problem lies in the following part of the decompiled code:
```c
    *(int32_t *)(v1 + 268) = my_strlen(text);
    printf("%d\n", *(int32_t *)(v1 + 268));
    return *(int32_t *)(v1 + 268);
```
Here, we failed to reconstruct a local variable as the original source code for the input binary looks like this:
```c
    size_t len = my_strlen(text);
    printf("%d\n", len);
    return len;
```
On Linux, the decompiled code with `*(int32_t *)(v1 + 268)` runs fine, but on macOS, it fails with `SIGABRT`. We should try to reconstruct the original local variable so we do not use that questionable access via `*(int32_t *)(v1 + 268)`.

**Comment by PeterMatula** [comment]
This test is currently passing in both TeacCity and our testing macOS server. However, the problem with an unrecognized variable is still present. I'm leaving this open.
